name: ems_mobile
description: Geo-Attendance System Mobile App

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # HTTP & API
  http: ^1.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Location Services
  geolocator: ^10.1.0
  url_launcher: ^6.2.4
  device_info_plus: ^10.1.0 # For Device Binding
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.9
  
  # Date/Time
  intl: ^0.18.1
  table_calendar: ^3.0.9
  file_picker: ^8.0.5
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AKHpng_padded.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/AKHpng_padded.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/AKHpng_padded.png"
  android_12:
    color: "#FFFFFF"
    image: "assets/AKHpng_padded.png"

flutter:
  uses-material-design: true
  assets:
    - assets/AKHpng.png
